// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_title_ from "./routes/[title].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog from "./routes/blog.tsx";
import * as $index from "./routes/index.tsx";
import * as $BlogSidebar from "./islands/BlogSidebar.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $Logo from "./islands/Logo.tsx";
import * as $NavBar from "./islands/NavBar.tsx";
import * as $NavWrappedPage from "./islands/NavWrappedPage.tsx";
import * as $Post from "./islands/Post.tsx";
import * as $RandomPost from "./islands/RandomPost.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[title].tsx": $_title_,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog.tsx": $blog,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BlogSidebar.tsx": $BlogSidebar,
    "./islands/Counter.tsx": $Counter,
    "./islands/Hero.tsx": $Hero,
    "./islands/Logo.tsx": $Logo,
    "./islands/NavBar.tsx": $NavBar,
    "./islands/NavWrappedPage.tsx": $NavWrappedPage,
    "./islands/Post.tsx": $Post,
    "./islands/RandomPost.tsx": $RandomPost,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
